type User {
  id: String
  name: String
  email: String
  roles: [String!]
}

type Query {
  user(email: String): User
}

type Mutation {
  updateUser(id: String!, name: String, email: String, password: String): User
}

