type User {
  id: String
  name: String
  email: String
  roles: [String!]
}

type LoginResponse {
  token: String
}

type Query {
  user(email: String): User

  login(email: String, password: String): LoginResponse
}

type Mutation {
  updateUser(id: String!, name: String, email: String, password: String): User
}

